# Base configs
baseurl: "https://jayhope.me"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Jay Hope Photography"
subtitle: "See the world through my eyes!"
author: "Jay Hope"
header:
 title: "Photography"
 subtitle: "by Jay Hope"
footer:
 name: "Hey there, my name is Jay"
 bio: "I love nature and photography. My best photos are of something natural outdoors!"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/rampatra/photography\">fork this repo on github</a> ;)"
web_design: "-"

social_urls:
  twitter: ""
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
